// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FoxyProxy")>]
[<assembly: AssemblyProductAttribute("FoxyProxy")>]
[<assembly: AssemblyDescriptionAttribute("A debugging proxy hosted in fsi")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FoxyProxy"
    let [<Literal>] AssemblyProduct = "FoxyProxy"
    let [<Literal>] AssemblyDescription = "A debugging proxy hosted in fsi"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
    let [<Literal>] AssemblyConfiguration = "Release"
